# ATTENTION: NE COMMITEZ JAMAIS CE FICHIER AVEC DES SECRETS EN CLAIR DANS UN DÉPÔT PUBLIC
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
data:
  # REMPLACER par le mot de passe RDS encodé en Base64 : echo -n 'password' | base64
  DB_PASSWORD: "REMPLACER_EN_BASE64"
  # REMPLACER par le nom d'utilisateur RDS encodé en Base64
  DB_USER: "REMPLACER_EN_BASE64"
  # REMPLACER par l'endpoint RDS principal (écriture) encodé en Base64
  DB_WRITER_HOST: "REMPLACER_EN_BASE64"
  # REMPLACER par une clé API secrète encodée en Base64
  API_SECRET_KEY: "REMPLACER_EN_BASE64"
